<?php

require ('vendor/autoload.php');


$agent = new Yekhlakov\PAgent\Agent(llm: "local");


$agent
->withTools('filesystem')
->handle(
"
Assume that all files are in local file system.
Assume class and file names follow usual php notation, for example, a class `Yekhlakov\\PAgent\\Traits\\CurlTrait` is in the file `src/Traits/CurlTrait.php`.
1. Explore the class `Yekhlakov\\PAgent\\Agent`.
2. Also explore all used traits.
3. Produce a description of this program: its purpose, principles of operation, required configuration variables etc.
4. Mention in the end of the description that it was generated by you.
5. Write the description you produced to local file `README.md` (overwriting its old contents)
");

