<?php

require ('vendor/autoload.php');


$agent = new Yekhlakov\PAgent\Agent(llm: "local");


$agent
->withTools('filesystem')
->handle(
"
Assume that all files are in local file system.
Assume class and file names follow usual php notation, for example, a class `Yekhlakov\\PAgent\\Traits\\CurlTrait` is in the file `src/Traits/CurlTrait.php`.

**IMPORTANT**: The README you produce is intended to be posted into public repository. Formulate appropriately.

**Task steps**:
1. Explore the class `Yekhlakov\\PAgent\\Agent`.
2. Also explore ALL used traits (you MUST fetch their program code with your tools).
3. Produce a description of this program: its purpose, principles of operation, required configuration variables etc.
4. In a separate section describe the tools available to the Agent. Produce the list of tools as a table containing tool name and description.
   Extract tool names and descriptions from the program code.
5. Mention in the end of the description that it was generated by this very Agent (you).
6. WRITE the description you produced to local file `README.md` (overwriting its old contents) and finish work.
");

